### ISSUE TITLE
[Meta] Code directive capabilities

### ISSUE THREAD

**Issue by bmorelli25** [elastic/docs-builder#56]
### Summary

tbd

### Requirements

**For 9.0**

- [ ] https://github.com/elastic/docs-builder/issues/7 (Basic functionality)
- [ ] #102
- [ ] https://github.com/elastic/docs-builder/issues/55

**Post 9.0**

- [ ] https://github.com/elastic/docs-builder/issues/52
